name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm ci
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm ci
        
    - name: Install E2E test dependencies
      working-directory: ./e2e-tests
      run: |
        npm ci
        npx playwright install --with-deps
        
    - name: Setup database
      working-directory: ./backend
      run: |
        npm run db:migrate
        npm run db:seed:test
        
    - name: Start backend server
      working-directory: ./backend
      run: |
        npm run start:test &
        npx wait-on http://localhost:4000/health
        
    - name: Start frontend server
      working-directory: ./frontend
      run: |
        npm run build
        npm run preview &
        npx wait-on http://localhost:3000
        
    - name: Run E2E tests
      working-directory: ./e2e-tests
      run: |
        npm test
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: e2e-tests/playwright-report/
        retention-days: 30
        
    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-videos
        path: e2e-tests/test-results/
        retention-days: 7